# core/auth_components.py
from fasthtml.common import *
from django.middleware.csrf import get_token

# A reusable component for rendering forms
def FormLayout(request, form, *, title: str, submit_text: str):
    csrf_token = get_token(request)

    # We will build the non-field-errors section conditionally
    non_field_errors_display = []
    if form.non_field_errors():
        non_field_errors_display.append(
            # Create your own structure for the errors
            Div(
                H4("Please correct the errors below:"),
                Ul(*[Li(error) for error in form.non_field_errors()]),
                # You can add any classes you want for styling
                cls="alert alert-danger"
            )
        )
    form_layout = Div(
        H2(title),
        # Display non-field errors (e.g., "Invalid credentials")
        # Render our custom-built error display
        *non_field_errors_display,
        Form(
            Input(type='hidden', name='csrfmiddlewaretoken', value=csrf_token),
            # Raw() is crucial to render the HTML generated by Django's form methods
            # Raw(form.as_p()),
            NotStr(form.as_p()),
            Button(submit_text, type='submit'),
            cls="form-container"
        )
    )
    return form_layout

# Specific component for the login page
def LoginPageComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Log In",
        submit_text="Log In"
    )

# Specific component for the signup page
def SignupPageComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Sign Up",
        submit_text="Sign Up"
    )