# core/auth_components.py
from django.urls import reverse
from fasthtml.common import *
from django.middleware.csrf import get_token

# A reusable component for rendering forms
def FormLayout(request, form, *, title: str, submit_text: str):
    csrf_token = get_token(request)

    # We will build the non-field-errors section conditionally
    non_field_errors_display = []
    if form.non_field_errors():
        non_field_errors_display.append(
            # Create your own structure for the errors
            Div(
                H4("Please correct the errors below:"),
                Ul(*[Li(error) for error in form.non_field_errors()]),
                # You can add any classes you want for styling
                cls="alert alert-danger"
            )
        )
    form_layout = Div(
        H2(title),
        # Display non-field errors (e.g., "Invalid credentials")
        # Render our custom-built error display
        *non_field_errors_display,
        Form(
            Input(type='hidden', name='csrfmiddlewaretoken', value=csrf_token),
            # Raw() is crucial to render the HTML generated by Django's form methods
            # Raw(form.as_p()),
            NotStr(form.as_p()),
            Button(submit_text, type='submit'),
            cls="form-container"
        )
    )
    return form_layout

# Specific component for the login page
def LoginPageComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Log In",
        submit_text="Log In"
    )

# Specific component for the signup page
def SignupPageComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Sign Up",
        submit_text="Sign Up"
    )

# --- NEW COMPONENTS FOR PASSWORD RESET ---

# Component for the page where the user requests a password reset
def PasswordResetRequestComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Reset Your Password",
        submit_text="Send Reset Email"
    )

# Component for the "email sent" confirmation page
def PasswordResetDoneComponent():
    return Div(
        H2("Password Reset Email Sent"),
        P("We have sent you an email with instructions on how to reset your password. Please check your inbox.")
    )

# Component for the page where the user enters their new password
def PasswordResetFromKeyComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Choose a New Password",
        submit_text="Set New Password"
    )

# Component for the "password successfully changed" confirmation page
def PasswordResetFromKeyDoneComponent():
    return Div(
        H2("Password Successfully Reset"),
        P("You can now log in with your new password."),
        A("Log In Now", href=reverse('account_login'), cls="button")
    )


# --- NEW COMPONENT FOR PASSWORD CHANGE (for logged-in users) ---
def PasswordChangeComponent(request, form):
    return FormLayout(
        request,
        form,
        title="Change Your Password",
        submit_text="Save New Password"
    )