# Generated by Django 5.0.7 on 2024-07-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailformpage_formfield'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailFormPage',
            new_name='ContactPage',
        ),
    ]
