# Generated by Django 5.1 on 2024-10-13 02:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='blog.blogpage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='blog.comment'),
        ),
    ]
