# Generated by Django 5.0.7 on 2024-07-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagetag_blogpage_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpagetag',
            table='blog_page_tags',
        ),
    ]
