# Generated by Django 5.0.7 on 2024-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
