# Generated by Django 5.0.7 on 2024-07-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_rename_brandsetting_brandsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsettings',
            name='logo',
        ),
        migrations.DeleteModel(
            name='FooterLinks',
        ),
        migrations.DeleteModel(
            name='BrandSettings',
        ),
    ]
