# Generated by Django 5.0.7 on 2024-07-10 08:44

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_income_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budgets.category')),
            ],
            options={
                'verbose_name': 'Budget Item',
                'db_table': 'budgets',
                'unique_together': {('category', 'date')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
