# Generated by Django 5.0.7 on 2024-07-10 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_budgetitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(db_index=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('user', 'category', 'date')},
        ),
    ]
